### ISSUE TITLE
How to enable batch size > 1?Any advices?

### ISSUE THREAD

**Issue by TyroneLi** [Scalsol/mega.pytorch#3]

**Comment by TyroneLi** [comment]
I find that setting batch_size > 1 in config file could continue training. So is that right? Or it is the wrong way to use batch_size > 1?

**Comment by TyroneLi** [comment]
> I find that setting batch_size > 1 in config file could continue training. So is that right? Or it is the wrong way to use batch_size > 1?

Oh I found even doing that, training procedure still using batch_size = 1.

**Comment by Scalsol** [comment]
If you want to use batch size > 1, you should first change the behavior of **BatchCollator** in [mega_core/data/collate_batch.py](https://github.com/Scalsol/mega.pytorch/blob/master/mega_core/data/collate_batch.py). Then you should modify [mega_core/engine/trainer.py](https://github.com/Scalsol/mega.pytorch/blob/master/mega_core/engine/trainer.py) and [mega_core/engine/inference.py](https://github.com/Scalsol/mega.pytorch/blob/master/mega_core/engine/inference.py) to make the training and inference procedure compatible with the behavior of   **BatchCollator**. And also the model should modified correspondingly. Setting batch_size > 1  is the wrong way. Because the **BatchCollator** only use 1 image.
