### ISSUE TITLE
ImportError: can't import name '_C'

### ISSUE THREAD

**Issue by humble-king** [Scalsol/mega.pytorch#34]
On running the demo.py code, I am getting an import error 

`from mega_core import _C `
`ImportError: cannot import name '_C'`

This error was coming from `./mega_core/layers/nms.py` and some other files in the same directory

so I commented it and changed it as 

`#from mega_core import _C`
`from ._utils import _C`

After making the changes the code worked and I was able to get my predictions. Are the two things same? I want to know whether I did the correct thing or not. It would be great if someone could give help in this regard.

**Comment by Skydddoogg** [comment]
`ImportError: cannot import name '_C'` was raised because you did not build MEGA (`mega.pytorch`) or the building process is failed.

Please check this below step in `INSTALL.md` carefully.
<img width="468" alt="Screen Shot 2563-07-05 at 01 59 22" src="https://user-images.githubusercontent.com/20947581/86519277-51b3d080-be63-11ea-8869-0ef531040e0a.png">

**Comment by humble-king** [comment]
Thanks a lot @Skydddoogg . It is working now
